apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE HTML>

    <html>

    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>Title</title>
    </head>

    <body>

      <header>
        <nav>
          <ul>
            <li>Your menu</li>
          </ul>
        </nav>
      </header>
      
      <section>
      
        <article>
          <header>
            <h2>Article title</h2>
            <p>Posted on <time datetime="2019-09-04T16:31:24+02:00">September 4th 2019</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
          </header>
          <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
        </article>
        
        <article>
          <header>
            <h2>Article title</h2>
            <p>Posted on <time datetime="2019-09-04T16:31:24+02:00">September 4th 2019</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
          </header>
          <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
        </article>
        
      </section>

      <aside>
        <h2>About section</h2>
        <p>Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
      </aside>

      <footer>
        <p>Copyright 2019 Marcin Pyrka</p>
      </footer>

    </body>

    </html>
